SUBJECT_MAP = [
    # ── Social, Humanitarian & Cultural (Third Committee) ─────────────────────
    ("HUMAN RIGHTS",                                    "Social, Humanitarian & Cultural"),
    ("RACIAL DISCRIMINATION",                           "Social, Humanitarian & Cultural"),
    ("RIGHTS OF THE CHILD",                             "Social, Humanitarian & Cultural"),
    ("WOMEN'S ADVANCEMENT",                             "Social, Humanitarian & Cultural"),
    ("WOMEN--",                                         "Social, Humanitarian & Cultural"),
    ("INDIGENOUS PEOPLE",                               "Social, Humanitarian & Cultural"),
    ("TORTURE",                                         "Social, Humanitarian & Cultural"),
    ("REFUGEES",                                        "Social, Humanitarian & Cultural"),
    ("MIGRATION",                                       "Social, Humanitarian & Cultural"),
    ("ELECTIONS",                                       "Social, Humanitarian & Cultural"),
    ("SOCIAL DEVELOPMENT",                              "Social, Humanitarian & Cultural"),
    ("SOCIAL CONDITIONS",                               "Social, Humanitarian & Cultural"),
    ("HEALTH",                                          "Social, Humanitarian & Cultural"),
    ("HUMAN SETTLEMENTS",                               "Social, Humanitarian & Cultural"),
    ("CULTURE--",                                       "Social, Humanitarian & Cultural"),
    ("CULTURAL PROPERTY",                               "Social, Humanitarian & Cultural"),
    ("FOOD",                                            "Social, Humanitarian & Cultural"),
    ("RIGHT TO FOOD",                                   "Social, Humanitarian & Cultural"),
    ("FOOD SECURITY",                                   "Social, Humanitarian & Cultural"),
    ("SCIENCE AND TECHNOLOGY--HUMAN RIGHTS",            "Social, Humanitarian & Cultural"),

    # ── Palestine & Middle East (UN Plenary — special status) ─────────────────
    ("TERRITORIES OCCUPIED BY ISRAEL",                  "Palestine & Middle East"),
    ("UNRWA",                                           "Palestine & Middle East"),
    ("PALESTINE QUESTION",                              "Palestine & Middle East"),
    ("MIDDLE EAST SITUATION",                           "Palestine & Middle East"),
    ("MIDDLE EAST--",                                   "Palestine & Middle East"),
    ("GOLAN HEIGHTS",                                   "Palestine & Middle East"),

    # ── Disarmament & International Security (First Committee) ────────────────
    ("DISARMAMENT",                                     "Disarmament & International Security"),
    ("NUCLEAR WEAPON",                                  "Disarmament & International Security"),
    ("NUCLEAR NON-PROLIFERATION",                       "Disarmament & International Security"),
    ("NUCLEAR-WEAPON-FREE ZONES",                       "Disarmament & International Security"),
    ("NON-NUCLEAR-WEAPON STATES",                       "Disarmament & International Security"),
    ("FISSIONABLE MATERIALS",                           "Disarmament & International Security"),
    ("DEPLETED URANIUM",                                "Disarmament & International Security"),
    ("COMPREHENSIVE NUCLEAR-TEST-BAN",                  "Disarmament & International Security"),
    ("ARMS RACE",                                       "Disarmament & International Security"),
    ("ARMS TRANSFERS",                                  "Disarmament & International Security"),
    ("CONVENTIONAL ARMS",                               "Disarmament & International Security"),
    ("CONVENTIONAL WEAPONS",                            "Disarmament & International Security"),
    ("MILITARY BUDGETS",                                "Disarmament & International Security"),
    ("VERIFICATION",                                    "Disarmament & International Security"),
    ("LANDMINES",                                       "Disarmament & International Security"),
    ("CLUSTER MUNITIONS",                               "Disarmament & International Security"),
    ("CHEMICAL WEAPONS",                                "Disarmament & International Security"),
    ("CHEMICAL AND BIOLOGICAL WARFARE",                 "Disarmament & International Security"),
    ("BIOLOGICAL WEAPONS",                              "Disarmament & International Security"),
    ("WEAPONS OF MASS DESTRUCTION",                     "Disarmament & International Security"),
    ("BALLISTIC MISSILES",                              "Disarmament & International Security"),
    ("IAEA",                                            "Disarmament & International Security"),
    ("WEAPONS--OUTER SPACE",                            "Disarmament & International Security"),
    ("ARMS RACE--OUTER SPACE",                          "Disarmament & International Security"),
    ("OUTER SPACE--ARMS RACE",                          "Disarmament & International Security"),
    ("OUTER SPACE--CONFIDENCE-BUILDING",                "Disarmament & International Security"),
    ("PEACE--CONVENTIONAL DISARMAMENT",                 "Disarmament & International Security"),
    ("SCIENCE AND TECHNOLOGY--INTERNATIONAL SECURITY",  "Disarmament & International Security"),
    ("SCIENCE AND TECHNOLOGY--DISARMAMENT",             "Disarmament & International Security"),
    ("INFORMATION--INTERNATIONAL SECURITY",             "Disarmament & International Security"),

    # ── Special Political & Decolonization (Fourth Committee) ────────────────
    ("DECOLONIZATION",                                  "Special Political & Decolonization"),
    ("SELF-DETERMINATION",                              "Special Political & Decolonization"),
    ("NON-SELF-GOVERNING TERRITORIES",                  "Special Political & Decolonization"),
    ("COLONIAL COUNTRIES",                              "Special Political & Decolonization"),
    ("APARTHEID",                                       "Special Political & Decolonization"),
    ("NAMIBIA",                                         "Special Political & Decolonization"),
    ("COMORIAN ISLAND",                                 "Special Political & Decolonization"),
    ("FALKLAND ISLANDS",                                "Special Political & Decolonization"),
    ("NATIONAL LIBERATION MOVEMENTS",                   "Special Political & Decolonization"),

    # ── Economic & Financial (Second Committee) ───────────────────────────────
    ("SUSTAINABLE DEVELOPMENT",                         "Economic & Financial"),
    ("AGENDA 21",                                       "Economic & Financial"),
    ("INTERNATIONAL TRADE",                             "Economic & Financial"),
    ("EXTERNAL DEBT",                                   "Economic & Financial"),
    ("COMMODITIES",                                     "Economic & Financial"),
    ("INDUSTRIAL DEVELOPMENT",                          "Economic & Financial"),
    ("TAXATION",                                        "Economic & Financial"),
    ("LAW OF THE SEA",                                  "Economic & Financial"),
    ("GLOBALIZATION",                                   "Economic & Financial"),
    ("ECONOMIC ASSISTANCE",                             "Economic & Financial"),
    ("ECONOMIC COOPERATION",                            "Economic & Financial"),
    ("ECONOMIC DEVELOPMENT",                            "Economic & Financial"),
    ("NEW INTERNATIONAL ECONOMIC ORDER",                "Economic & Financial"),
    ("DEVELOPMENT FINANCE",                             "Economic & Financial"),
    ("POVERTY",                                         "Economic & Financial"),
    ("AGRICULTURE",                                     "Economic & Financial"),
    ("AFRICA--DEVELOPMENT",                             "Economic & Financial"),
    ("SCIENCE AND TECHNOLOGY--DEVELOPMENT",             "Economic & Financial"),
    ("INFORMATION TECHNOLOGY--DEVELOPMENT",             "Economic & Financial"),

    # ── Environment & Climate ─────────────────────────────────────────────────
    ("CLIMATE CHANGE",                                  "Environment & Climate"),
    ("ENVIRONMENT",                                     "Environment & Climate"),
    ("STORMS",                                          "Environment & Climate"),
    ("DISASTER",                                        "Environment & Climate"),
    ("MARINE ECOSYSTEMS",                               "Environment & Climate"),
    ("SUSTAINABLE ENERGY",                              "Environment & Climate"),

    # ── International Peace & Security (UN Agenda section 1) ─────────────────
    ("INTERNATIONAL SECURITY",                          "International Peace & Security"),
    ("REGIONAL SECURITY",                               "International Peace & Security"),
    ("PEACE",                                           "International Peace & Security"),
    ("ARMED CONFLICTS",                                 "International Peace & Security"),
    ("CUBA--UNITED STATES",                             "International Peace & Security"),
    ("NICARAGUA--UNITED STATES",                        "International Peace & Security"),
    ("INDIAN OCEAN--ZONES OF PEACE",                    "International Peace & Security"),
    ("SOUTH ATLANTIC OCEAN REGION--ZONES OF PEACE",     "International Peace & Security"),
    ("UKRAINE--POLITICAL",                              "International Peace & Security"),
    ("AGGRESSION",                                      "International Peace & Security"),
    ("TERRORISM",                                       "International Peace & Security"),
    ("PEACEKEEPING",                                    "International Peace & Security"),
    ("CRIME PREVENTION",                                "International Peace & Security"),
    ("ILLICIT TRAFFIC",                                 "International Peace & Security"),
    ("UN DISENGAGEMENT OBSERVER FORCE",                 "International Peace & Security"),
    ("COLLECTIVE SECURITY",                             "International Peace & Security"),
    ("FORCE IN INTERNATIONAL RELATIONS",                "International Peace & Security"),
    ("ECONOMIC SANCTIONS",                              "International Peace & Security"),
    ("SITUATION",                                       "International Peace & Security"),

    # ── Global Governance (own construct) ────────────────────────────────────
    ("OUTER SPACE--PRINCIPLES",                         "Global Governance"),
    ("OUTER SPACE--PEACEFUL USES",                      "Global Governance"),
    ("ANTARCTICA",                                      "Global Governance"),
    ("INTERNET",                                        "Global Governance"),
    ("CYBERSPACE",                                      "Global Governance"),
    ("ORGANIZATION FOR SECURITY AND COOPERATION",       "Global Governance"),
    ("INTERNATIONAL CRIMINAL COURT",                    "Global Governance"),
    ("DISPUTE SETTLEMENT",                              "Global Governance"),
    ("GOOD NEIGHBOURLINESS",                            "Global Governance"),
    ("INFORMATION",                                     "Global Governance"),

    # ── Administrative, Budgetary & Legal (Fifth + Sixth Committee) ──────────
    ("UN--FINANCIAL SITUATION",                         "Administrative, Budgetary & Legal"),
    ("UN. ECONOMIC AND SOCIAL COUNCIL",                 "Administrative, Budgetary & Legal"),
    ("UN INTERIM FORCE",                                "Administrative, Budgetary & Legal"),
    ("UN CONFERENCES",                                  "Administrative, Budgetary & Legal"),
    ("UN--BUDGET",                                      "Administrative, Budgetary & Legal"),
    ("UN CHARTER",                                      "Administrative, Budgetary & Legal"),
    ("UN SYSTEM",                                       "Administrative, Budgetary & Legal"),
    ("UN REFORM",                                       "Administrative, Budgetary & Legal"),
    ("UNITED NATIONS--REFORM",                          "Administrative, Budgetary & Legal"),
    ("ORGANIZATION FOR DEMOCRACY",                      "Administrative, Budgetary & Legal"),
    ("UN. COMMITTEE",                                   "Administrative, Budgetary & Legal"),
    ("COUNCIL OF EUROPE--UN",                           "Administrative, Budgetary & Legal"),
    ("LEAGUE OF ARAB STATES",                           "Administrative, Budgetary & Legal"),
    ("PUBLIC INFORMATION",                              "Administrative, Budgetary & Legal"),
    ("PEACEKEEPING OPERATIONS--FINANCING",              "Administrative, Budgetary & Legal"),
    ("PEACEKEEPING OPERATIONS--REIMBURSEMENT",          "Administrative, Budgetary & Legal"),
    ("PEACE AND SECURITY--CODE OF OFFENCES",            "Administrative, Budgetary & Legal"),
]